export const GET_BUSES = 'GET_BUSES'
export const BUSES_ERROR = 'BUSES_ERROR'
export const GET_ARCHIVE = 'GET_ARCHIVE'
export const ARCHIVE_ERROR = 'ARCHIVE_ERROR'
export const ADD_BUS = 'ADD_BUS'
export const ADD_BUS_ERROR = 'ADD_BUS_ERROR'